on:
  push:
    branches:
      - main

env:
  GOOGLE_SHEETS_ID: 'sample'
  GOOGLE_SERVICE_ACCOUNT_KEY_BASE64: 'dGVzdA=='

jobs:
  update-coverage-badge:
    name: Update Repo Coverage Badge
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path:  '**/package-lock.json'
      
      - name: Install dependencies
        run: npm run install:all
      
      - name: Run tests
        run: npm test
        
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: we-cli/coverage-badge-action@main